on:
  push:
    branches: master

name: deploy-tutorials

jobs:
  deploy-tutorials:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_cran("rsconnect")
          remotes::install_cran("glue")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy tutorials
        run: source("scripts/deploy_on_travis.R")
        shell: Rscript {0}
